# PRUEBAS EN LOCALHOST CON UNA BASE DE DATOS LOCAL.

### GET
GET http://localhost:5000/products

###
GET http://localhost:5000/products/categories/futbol

### POST, Create product
POST http://localhost:5000/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTM5Njk2NDgsImV4cCI6MTcxMzk2OTg4OH0.eHYx7allOlSXg2M9ol0Fertyyr_shStT69_o8GxVvs0


{
 "title": "BOTINES COPA PURE II",
 "imageUrl": "https://imgs.search.brave.com/YnGyIaIvVTl0_tPAem3XV3Ov7IE121mhoG4Kf07Bs4Q/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9hc3Nl/dHMuYWRpZGFzLmNv/bS9pbWFnZXMvd18z/ODMsaF8zODMsZl9h/dXRvLHFfYXV0byxm/bF9sb3NzeSxjX2Zp/bGwsZ19hdXRvL2Zm/NzFkYjFjZTU5MDRm/ZjJhOWY3ODk4NjQ0/NTQ5ODRjXzkzNjYv/Ym90aW5lcy1jb3Bh/LXB1cmUtaWktbGVh/Z3VlLmpwZw",
 "description": "***UNISEX, HORMA GRANDE*** Para pies delgados recomendamos comprar el talle inferior.",
 "stock": 5,
 "price": 149999,
 "category": "futbol"
}

### GET user
GET http://localhost:5000/user
Content-Type: application/json

{
     "username": "santiago",
     "password": "**********"
}

### POST create user
POST http://localhost:5000/user
Content-Type: application/json

{
     "username": "prueba4",
     "first_name": "Santiago Emaunel",
     "last_name": "Mustafa Font",
     "email": "santiagomustafa4@gmail.com",
     "password": "thisismypassword"
}

### GET CART 
GET http://localhost:5000/cart
user_ID: 8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTQ0MTM3MTksImV4cCI6MTcxNDQxMzk1OX0.xOC2tbpTJPirLngwxDzRIfkQupYuOxR3VlQZCdDp5Ds

### POST CART
POST  http://localhost:5000/cart
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTQ0MTM3MTksImV4cCI6MTcxNDQxMzk1OX0.xOC2tbpTJPirLngwxDzRIfkQupYuOxR3VlQZCdDp5Ds
Content-Type: application/json

{
     "user_cart": "a97632a2-b974-4b7e-871f-bd17c3e14767",
     "user_id": 8
}

###
GET HTTP://LOCALHOST:5000/categories