# PRUEBAS EN LOCALHOST CON UNA BASE DE DATOS LOCAL.

### GET
GET http://localhost:1234/products

###
GET http://localhost:1234/products/categories/deportes

### POST, Create product
POST http://localhost:1234/products
Content-Type: application/json

{
 "title": "Pelota de Voley",
 "imageUrl": "https://monterosport.com.ar/wp-content/uploads/2016/08/pelota-voley-pintier-super-extra-1.jpg",
 "description": "Pelota de voley marca Prittier, calidad profesional para interior, industria Argentina.",
 "stock": 150,
 "category":"deportes",
 "price": 97650
}

### GET user
GET http://localhost:1234/user?username=pruebaNewUser1&password=prueba1234

### POST
POST http://localhost:1234/user
Content-Type: application/json

{
     "username": "prueba2",
     "first_name": "Santiago Emaunel",
     "last_name": "Mustafa Font",
     "email": "santiagomustafa1212@gmail.com",
     "password": "thisismypassword"
}